---
language: bash


sudo: false

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.16.0 TARGET_NODE_VERSION=0.12

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - npm install -g elm@$ELM_VERSION
  - elm package install -y
  - npm install elm-test

script:
  - bin/fetch-configlet
  - bin/configlet .
  - bin/build.sh

